#!/bin/bash
# This is a simple build script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

cartridge_type="python-2.7"
source $OPENSHIFT_HOMEDIR/$cartridge_type/activate_virtenv
#make sure we have Django installed
pip install Django==1.5