#!/bin/bash
# This is a simple build script and will be executed on your CI system if
# available.  Otherwise it will execute while your application is stopped
# before the deploy step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

source ~/python-2.6/activate-virtenv
pip install https://www.djangoproject.com/download/1.5c1/tarball/  